# Generated by Django 6.0.3 on 2026-03-29 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('test', 'Test / Exam'), ('trip', 'School Trip'), ('revision', 'Revision / Study Session'), ('holiday', 'Holiday / Break'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='upcoming', max_length=20)),
            ],
            options={
                'verbose_name': 'Academic Event',
                'verbose_name_plural': 'Academic Calendar',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Grade 1, JSS 2, SS 3, Primary 4', max_length=100, unique=True)),
                ('tuition_fee', models.DecimalField(decimal_places=2, help_text='Total school fees for this grade level (e.g. 150000.00)', max_digits=12)),
                ('description', models.CharField(blank=True, help_text="Optional note, e.g. 'Junior Secondary — Science track'", max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the display order. Lower number = appears first.')),
            ],
            options={
                'verbose_name': 'Grade Level',
                'verbose_name_plural': 'Grade Levels & Tuition',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Full name of the student', max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', help_text="Student's gender", max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if student has left the school')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('grade_level', models.ForeignKey(help_text="Select the student's grade — tuition will be set automatically", on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.gradelevel')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['student_name'],
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees_due', models.DecimalField(decimal_places=2, help_text="Auto-populated from the student's grade level tuition fee", max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid so far — cannot exceed total fees due', max_digits=12)),
                ('payment_status', models.CharField(choices=[('fully_paid', 'Fully Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20)),
                ('last_payment_date', models.DateField(blank=True, help_text='Date of the most recent payment', null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='school.student')),
            ],
            options={
                'verbose_name': 'Finance Record',
                'verbose_name_plural': 'Finance Records',
                'ordering': ['student__student_name'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(choices=[('warning', 'Warning'), ('detention', 'Detention'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion')], max_length=20)),
                ('reason', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('issued_by', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='school.student')),
            ],
            options={
                'verbose_name': 'Discipline Record',
                'verbose_name_plural': 'Discipline Records',
                'ordering': ['-date'],
            },
        ),
    ]
