# Generated by Django 6.0.3 on 2026-04-04 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finance',
            options={},
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount received in this single installment', max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date this payment was received')),
                ('received_by', models.CharField(help_text='Name of the staff member (Bursar) who collected this payment', max_length=100)),
                ('receipt_number', models.CharField(blank=True, help_text='Auto-generated receipt number — do not edit manually', max_length=30, unique=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('pos', 'POS / Card')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Optional: any notes about this payment (e.g. 'Part payment for first term')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finance', models.ForeignKey(help_text="The student's finance record this payment applies to", on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='school.finance')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
